apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
spec:
  mode: daemonset
  serviceAccount: otel-collector-daemonset
  hostNetwork: true
  env:
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_http:
    processors:
      k8sattributes:
        filter:
          node_from_env_var: KUBE_NODE_NAME
    exporters:
      otlp:
        endpoint: "tempo-simplest-distributor:4317"
        tls:
          ca_file: server.crt
          cert_file: client.crt
          key_file: client.key
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [k8sattributes]
          exporters: [otlp]
